osx_image: xcode7.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
before_script:
- brew update
- brew upgrade xctool || true
- pod setup
- pod install --project-directory=Example
script:
- xctool -workspace Example/PlaybasisSDK.xcworkspace -scheme PlaybasisSDK-Example -sdk iphonesimulator
- pod lib lint
